export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const POST_CATEGORY = "POST_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const POST_USER = "POST_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const ADD_TO_CART_LOCALSTORAGE = "ADD_TO_CART_LOCALSTORAGE";
export const GET_PRODUCT_CART_LOCALSTORAGE = "GET_PRODUCT_CART_LOCALSTORAGE";
export const DELETE_TOTAL_CART= "DELETE_TOTAL_CART";
export const DELETE_ITEMS_CART="DELETE_ITEMS_CART";
export const DELETE_CART_LS = "DELETE_CART_LS";
export const DELETE_ITEM_LC = "DELETE_ITEM_LC";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_COUNT_PRODUCT = "UPDATE_COUNT_PRODUCT"




